export const popularLandLocations = [
  {
    slug: 'bardoli',
    name: 'Bardoli',
    district: 'Surat',
    region: 'Surat',
    image: 'https://images.unsplash.com/photo-1518837695005-2083093ee35b?auto=format&fit=crop&w=1600&q=85',
    activeListings: 84,
    startingPrice: '₹18 Lakh',
    propertyTypes: ['Agricultural Land', 'Non-Agricultural Land'],
    description: 'A fast-growing corridor with strong road access and rising demand for agricultural and urban-edge land.',
    verifiedSellers: 44,
    activeBuyers: 128,
    propertiesSold: 19,
    averagePrice: '₹24 Lakh',
    highestPrice: '₹48 Lakh',
    lowestPrice: '₹12 Lakh',
    summary: ['Excellent road connectivity', 'Agricultural potential', 'Industrial growth', 'Residential development'],
    mapQuery: 'Bardoli, Surat, Gujarat',
    relatedLocations: ['Kamrej', 'Palsana', 'Olpad', 'Mandvi'],
  },
  {
    slug: 'kamrej',
    name: 'Kamrej',
    district: 'Surat',
    region: 'Surat',
    image: 'https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=1600&q=85',
    activeListings: 76,
    startingPrice: '₹22 Lakh',
    propertyTypes: ['Agricultural Land', 'Non-Agricultural Land'],
    description: 'A strategic location combining agricultural value with strong proximity to Surat’s expanding urban zones.',
    verifiedSellers: 37,
    activeBuyers: 109,
    propertiesSold: 16,
    averagePrice: '₹28 Lakh',
    highestPrice: '₹55 Lakh',
    lowestPrice: '₹15 Lakh',
    summary: ['Nearby highways', 'Railway connectivity', 'Markets', 'Schools and hospitals'],
    mapQuery: 'Kamrej, Surat, Gujarat',
    relatedLocations: ['Bardoli', 'Palsana', 'Olpad', 'Chikhli'],
  },
  {
    slug: 'gandevi',
    name: 'Gandevi',
    district: 'Navsari',
    region: 'Navsari',
    image: 'https://images.unsplash.com/photo-1547737699-6577b38d74bd?auto=format&fit=crop&w=1600&q=85',
    activeListings: 68,
    startingPrice: '₹16 Lakh',
    propertyTypes: ['Agricultural Land', 'Non-Agricultural Land'],
    description: 'A prominent Navsari sub-region with strong agricultural demand and growing investor interest.',
    verifiedSellers: 31,
    activeBuyers: 94,
    propertiesSold: 12,
    averagePrice: '₹21 Lakh',
    highestPrice: '₹41 Lakh',
    lowestPrice: '₹10 Lakh',
    summary: ['Agricultural potential', 'Water availability', 'Development potential', 'Nearby markets'],
    mapQuery: 'Gandevi, Navsari, Gujarat',
    relatedLocations: ['Jalalpore', 'Chikhli', 'Bilimora', 'Amalsad'],
  },
  {
    slug: 'chikhli',
    name: 'Chikhli',
    district: 'Navsari',
    region: 'Navsari',
    image: 'https://images.unsplash.com/photo-1542228262-3d0fbb325515?auto=format&fit=crop&w=1600&q=85',
    activeListings: 59,
    startingPrice: '₹14 Lakh',
    propertyTypes: ['Agricultural Land', 'Non-Agricultural Land'],
    description: 'A balanced location for long-term land investment with strong local demand and infrastructure access.',
    verifiedSellers: 28,
    activeBuyers: 83,
    propertiesSold: 10,
    averagePrice: '₹19 Lakh',
    highestPrice: '₹36 Lakh',
    lowestPrice: '₹9 Lakh',
    summary: ['Road connectivity', 'Industrial growth', 'Good water availability', 'Educational access'],
    mapQuery: 'Chikhli, Navsari, Gujarat',
    relatedLocations: ['Gandevi', 'Jalalpore', 'Bilimora', 'Amalsad'],
  },
  {
    slug: 'bilimora',
    name: 'Bilimora',
    district: 'Navsari',
    region: 'Navsari',
    image: 'https://images.unsplash.com/photo-1548837257609-643056a9970c?auto=format&fit=crop&w=1600&q=85',
    activeListings: 63,
    startingPrice: '₹20 Lakh',
    propertyTypes: ['Agricultural Land', 'Non-Agricultural Land'],
    description: 'A thriving Navsari market town with diverse demand for farmland, plots, and investor-ready land.',
    verifiedSellers: 33,
    activeBuyers: 97,
    propertiesSold: 14,
    averagePrice: '₹25 Lakh',
    highestPrice: '₹44 Lakh',
    lowestPrice: '₹13 Lakh',
    summary: ['Nearby highways', 'Industrial zone access', 'Residential development', 'High demand'],
    mapQuery: 'Bilimora, Navsari, Gujarat',
    relatedLocations: ['Gandevi', 'Chikhli', 'Jalalpore', 'Amalsad'],
  },
  {
    slug: 'amalsad',
    name: 'Amalsad',
    district: 'Navsari',
    region: 'Navsari',
    image: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1600&q=85',
    activeListings: 49,
    startingPrice: '₹12 Lakh',
    propertyTypes: ['Agricultural Land', 'Non-Agricultural Land'],
    description: 'A promising agricultural belt with strong demand for low-entry land purchase and future appreciation.',
    verifiedSellers: 26,
    activeBuyers: 78,
    propertiesSold: 9,
    averagePrice: '₹17 Lakh',
    highestPrice: '₹35 Lakh',
    lowestPrice: '₹8 Lakh',
    summary: ['Agricultural zone', 'Water availability', 'Development potential', 'Rural investment value'],
    mapQuery: 'Amalsad, Navsari, Gujarat',
    relatedLocations: ['Bilimora', 'Chikhli', 'Gandevi', 'Jalalpore'],
  },
];

export const getLocationBySlug = (slug) => popularLandLocations.find((location) => location.slug === slug) || null;
