export const popularLandLocations = [
  {
    slug: 'bardoli',
    name: 'Bardoli',
    district: 'Surat',
    region: 'Surat',
    image: 'https://images.unsplash.com/photo-1518837695005-2083093ee35b?auto=format&fit=crop&w=1600&q=85',
    activeListings: 84,
    startingPrice: '₹18 Lakh',
    propertyTypes: ['Agricultural Land', 'Non-Agricultural Land'],
    description: 'A fast-growing corridor with strong road access and rising demand for agricultural and urban-edge land.',
    verifiedSellers: 44,
    activeBuyers: 128,
    propertiesSold: 19,
    averagePrice: '₹24 Lakh',
    highestPrice: '₹48 Lakh',
    lowestPrice: '₹12 Lakh',
    summary: ['Excellent road connectivity', 'Agricultural potential', 'Industrial growth', 'Residential development'],
    mapQuery: 'Bardoli, Surat, Gujarat',
    relatedLocations: ['Majura', 'Palsana', 'Udhna', 'Gandevi'],
  },
  {
    slug: 'majura',
    name: 'Majura',
    district: 'Surat',
    region: 'Surat',
    image: 'https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=1600&q=85',
    activeListings: 76,
    startingPrice: '₹22 Lakh',
    propertyTypes: ['Agricultural Land', 'Non-Agricultural Land'],
    description: 'A strategic location combining agricultural value with strong proximity to Surat’s expanding urban zones.',
    verifiedSellers: 37,
    activeBuyers: 109,
    propertiesSold: 16,
    averagePrice: '₹28 Lakh',
    highestPrice: '₹55 Lakh',
    lowestPrice: '₹15 Lakh',
    summary: ['Nearby highways', 'Railway connectivity', 'Markets', 'Schools and hospitals'],
    mapQuery: 'Majura, Surat, Gujarat',
    relatedLocations: ['Bardoli', 'Palsana', 'Udhna', 'Gandevi'],
  },
  {
    slug: 'palsana',
    name: 'Palsana',
    district: 'Surat',
    region: 'Surat',
    image: 'https://images.unsplash.com/photo-1547737699-6577b38d74bd?auto=format&fit=crop&w=1600&q=85',
    activeListings: 68,
    startingPrice: '₹20 Lakh',
    propertyTypes: ['Agricultural Land', 'Non-Agricultural Land'],
    description: 'A rapidly developing hub with excellent industrial and agricultural prospects in Surat.',
    verifiedSellers: 35,
    activeBuyers: 112,
    propertiesSold: 15,
    averagePrice: '₹26 Lakh',
    highestPrice: '₹50 Lakh',
    lowestPrice: '₹14 Lakh',
    summary: ['Industrial growth', 'Highway access', 'High demand', 'Development potential'],
    mapQuery: 'Palsana, Surat, Gujarat',
    relatedLocations: ['Bardoli', 'Majura', 'Udhna', 'Gandevi'],
  },
  {
    slug: 'udhna',
    name: 'Udhna',
    district: 'Surat',
    region: 'Surat',
    image: 'https://images.unsplash.com/photo-1542228262-3d0fbb325515?auto=format&fit=crop&w=1600&q=85',
    activeListings: 72,
    startingPrice: '₹25 Lakh',
    propertyTypes: ['Agricultural Land', 'Non-Agricultural Land'],
    description: 'A key commercial and industrial zone in Surat offering high land appreciation.',
    verifiedSellers: 40,
    activeBuyers: 120,
    propertiesSold: 18,
    averagePrice: '₹30 Lakh',
    highestPrice: '₹60 Lakh',
    lowestPrice: '₹18 Lakh',
    summary: ['Commercial hub', 'Railway access', 'High demand', 'Industrial growth'],
    mapQuery: 'Udhna, Surat, Gujarat',
    relatedLocations: ['Bardoli', 'Majura', 'Palsana', 'Gandevi'],
  },
  {
    slug: 'navsari-city',
    name: 'Navsari City',
    district: 'Navsari',
    region: 'Navsari',
    image: 'https://images.unsplash.com/photo-1548837257609-643056a9970c?auto=format&fit=crop&w=1600&q=85',
    activeListings: 80,
    startingPrice: '₹24 Lakh',
    propertyTypes: ['Agricultural Land', 'Non-Agricultural Land'],
    description: 'The urban heart of Navsari district featuring premium plot and commercial land investments.',
    verifiedSellers: 42,
    activeBuyers: 130,
    propertiesSold: 20,
    averagePrice: '₹32 Lakh',
    highestPrice: '₹65 Lakh',
    lowestPrice: '₹16 Lakh',
    summary: ['Urban center', 'High demand', 'Infrastructure access', 'Residential development'],
    mapQuery: 'Navsari City, Navsari, Gujarat',
    relatedLocations: ['Gandevi', 'Bardoli', 'Palsana'],
  },
  {
    slug: 'gandevi',
    name: 'Gandevi',
    district: 'Navsari',
    region: 'Navsari',
    image: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1600&q=85',
    activeListings: 64,
    startingPrice: '₹16 Lakh',
    propertyTypes: ['Agricultural Land', 'Non-Agricultural Land'],
    description: 'A prominent Navsari sub-region with strong agricultural demand and growing investor interest.',
    verifiedSellers: 31,
    activeBuyers: 94,
    propertiesSold: 12,
    averagePrice: '₹21 Lakh',
    highestPrice: '₹41 Lakh',
    lowestPrice: '₹10 Lakh',
    summary: ['Agricultural potential', 'Water availability', 'Development potential', 'Nearby markets'],
    mapQuery: 'Gandevi, Navsari, Gujarat',
    relatedLocations: ['Navsari City', 'Bardoli', 'Palsana'],
  },
];

export const getLocationBySlug = (slug) => popularLandLocations.find((location) => location.slug === slug) || null;
